spring:
  application:
    name: mercor-scd-service-dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:employment-dev}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_MIN_IDLE:5}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      pool-name: SCDHikariCP
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: ${JPA_BATCH_SIZE:50}
          fetch_size: ${JPA_FETCH_SIZE:50}
          time_zone: UTC
        order_inserts: true
        order_updates: true
        format_sql: true
    show-sql: true

  # Add these Redis configuration properties
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000
    database: 0

  # Enable caching explicitly
  cache:
    type: redis
    redis:
      time-to-live: 86400000  # 1 day in milliseconds (matches your config)
      cache-null-values: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-dev.xml
    enabled: ${LIQUIBASE_ENABLED:true}
    default-schema: ${DB_SCHEMA:public}

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: ${COMPRESSION_ENABLED:true}
    mime-types: ${COMPRESSION_MIME_TYPES:application/json,application/xml,text/html,text/plain}
    min-response-size: ${COMPRESSION_MIN_SIZE:1024}

# Springdoc OpenAPI configuration
springdoc:
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    path: swagger-ui.html
  api-docs:
    enabled: true

# gRPC configuration
grpc:
  server:
    port: 50051
    reflection-service-enabled: true

logging:
  level:
    root: INFO
    com.mercor.assignment.scd: INFO
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG