global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # PostgreSQL metrics via exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics via exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Spring Boot application in Docker
  - job_name: 'mercor-scd-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mercor-scd-service:8080']
